### ISSUE TITLE
[1.17.1] Server crashes when attempting to load Rustic Regenerated on a server.

### ISSUE THREAD

**Issue by Gbergz** [Angular-Angel/Rustic-Regenerated#5]
Title ^

**Minecraft**: 1.17.1
**Forge**: 37.0.27
**Rustic Regenerated**: 1.1.1-RELEASE

**Crash-Report:** https://gist.github.com/Gbergz/dbf86abf2fa113b30236f933707ab157

**Comment by Angular-Angel** [comment]
Huh, I didn't think to check it for dedicated servers. Good catch! :X

**Comment by Angular-Angel** [comment]
Yeah okay, I fixed it, at least for when it's running as the only mod on my local dedicated test server. I'll be uploading the fix as 1.2.2-BETA shortly. If you have more issues, please also post a link to the modpack you're using on your server, if possible.

**Comment by Gbergz** [comment]
Thanks for the fix, and will do. 👍
